describe('Teste de interface na pagina inicial do google glass',()=>{
    beforeEach(()=>{
        cy.visit('../../../src/index.html')
    })
    it('Verificando Titulo da Pagina',()=>{
        cy.title().should('be.equal','Tudo sobre Google Glass');
    })
    it('Verificando links da pagina ',()=>{
        cy.contains('a','Home').should('be.visible').click()
        cy.contains('a','Especificações').should('be.visible').click()
        cy.contains('a','Fotos').should('be.visible').click()
        cy.contains('a','Multimídia').should('be.visible').click()
        cy.contains('a','Fale conosco').should('be.visible').click()
        cy.contains('a','Project Glass').should('have.attr','target','_blank').invoke('removeAttr','target')
        cy.contains('a','Facebook').should('have.attr','target','_blank').invoke('removeAttr','target')
        cy.contains('a',' Twitter').should('have.attr','target','_blank').invoke('removeAttr','target')        
    })
    it('Verificando fotos',()=>{
        cy.get('.foto-legenda').should('be.visible')
    })
    it.only('Verificando titulos e subtitulos',()=>{
        cy.contains('h1','Google Glass').should('be.visible')
        cy.contains('h1','Saiba tudo sobre o Google Glass').should('be.visible')
        cy.contains('h1','Menu Principal').should('be.not.visible').invoke('show').should('be.visible')
        cy.contains('h1','Outras Notícias').should('be.visible')
        cy.contains('h2','A revolução do Google está chegando').should('be.visible')
        cy.contains('h2','por Gustavo Guanabara').should('be.visible')
        cy.contains('h2','O que é').should('be.visible')
        cy.contains('h2','Google Glass').should('be.visible')
        cy.contains('h2','Especificações Técnicas').should('be.visible')
        cy.contains('h2','Como funciona').should('be.visible')
        cy.contains('h2','que você pode fazer com o Google Glasses').should('be.visible')
        cy.contains('h2','Vídeo mais recente').should('be.visible')
        cy.contains('h3','Tecnologia > Inovações').should('be.visible')
        cy.contains('h3',' Atualizado em 23/Abril/2013').should('be.visible').invoke('show').should('be.visible')
        cy.contains('h3','Google Glass').should('be.not.visible')
        cy.contains('caption','Técnica do Google Glass ').should('be.visible')
        cy.get('tbody tr').should('have.length',6)
    })
})